---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${CI_HOSTNAME}-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: ghcr.io/rheinwerk/molecule:${MOLECULE_DISTRO}
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: yes
      callbacks_enabled: timer, profile_tasks, yaml
      display_failed_stderr: true
      fact_caching: jsonfile
      fact_caching_connection: '/tmp'
      host_key_checking: false
      remote_tmp: '/tmp/.ansible-${USER}/tmp'
      stdout_callback: yaml
      roles_path: roles-lib
    diff:
      always: true
  playbooks:
    converge: ${MOLECULE_CONVERGE_PLAYBOOK:-converge.yml}
  log: True
verifier:
  name: ansible
