---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ${CI_HOSTNAME}-${CI_PROJECT_NAME_MOLECULE}-${CI_JOB_ID}
    image: ghcr.io/rheinwerk/molecule:${MOLECULE_DISTRO}
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    cgroupns_mode: private
    override_command: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    registry:
      url: ghcr.io
      credentials:
        username: ${GITHUB_ACTOR}
        password: ${GITHUB_TOKEN}
provisioner:
  name: ansible
  config_options:
    defaults:
      bin_ansible_callbacks: yes
      callbacks_enabled: ansible.posix.timer, ansible.posix.profile_tasks
      display_failed_stderr: true
      host_key_checking: false
      remote_tmp: '/tmp/.ansible-${USER}/tmp'
      callback_result_format: yaml
    diff:
      always: true
    callback_profile_tasks:
      task_output_limit: all
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK_PREPARE:-prepare.yml}
    cleanup: ${MOLECULE_PLAYBOOK_CLEANUP:-cleanup.yml}
    converge: ${MOLECULE_PLAYBOOK_CONVERGE:-converge.yml}
    destroy: ${MOLECULE_PLAYBOOK_DESTROY:-destroy.yml}
  log: True
  env:
    ANSIBLE_ROLES_PATH: ${GITHUB_WORKSPACE}:${HOME}/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:$MOLECULE_PROJECT_DIRECTORY/roles
verifier:
  name: ansible